config/routes.rb
Rails.application.routes.draw do
  root to: "main#index"
  get "about", to: "main#about"

  post "dog/search", to: "dog#search"
  post "dog/upvote/:id", to: "dog#upvote"
  resources :dog, only: %i[index show]

  resources :owner, only: %i[index show]

  resources :breed, only: %i[index show]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/breed.rb
class Breed < ApplicationRecord
  has_many :sub, class_name:  "Breed",
                 foreign_key: "parent_id"
  has_many :breed_dogs

  belongs_to :parent, class_name: "Breed", optional: true

  validates :title, presence: true
end

app/models/breed_dog.rb
class BreedDog < ApplicationRecord
  belongs_to :breed
  belongs_to :dog
end

app/models/dog.rb
class Dog < ApplicationRecord
  belongs_to :owner
  has_many :breed_dogs

  has_one_attached :image

  validates :name, :age, :size, presence: true
  validates :name, uniqueness: true
  validates :likes, numericality: true
end

app/models/owner.rb
class Owner < ApplicationRecord
  has_many :dogs

  has_one_attached :picture

  validates :name, :age, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/breed_controller.rb
class BreedController < ApplicationController
  def index
    @breeds = Breed.all.page(params[:page])
  end

  def show
    @breed = Breed.find(params[:id])
    @dogs = @breed.breed_dogs.map { |x| x.dog }
    @dogs = Kaminari.paginate_array(@dogs).page(params[:page])
  end
end

app/controllers/dog_controller.rb
class DogController < ApplicationController
  def index; end

  def show
    @dog = Dog.find(params[:id])
  end

  def search
    if (params[:search] != "") && params[:breed_id].to_i != 0
      breed_id = Breed.find(params[:breed_id].to_i).id
      # @dogs = Dog.where("lower(name) LIKE :search",
      #                   search: "%#{params[:search]}%").map do |x|
      #   if x.breed_dogs.index do |y|
      #        y.breed_id == breed_id
      #      end.nil?
      #     return x
      #   end
      # end
      @dogs = Dog.joins(:breed_dogs)
                 .where("lower(name) LIKE :search",
                        search: "%#{params[:search]}%")
                 .where('breed_dogs.breed_id': breed_id)
    elsif (params[:search] != "") && params[:breed_id].to_i == 0
      @dogs = Dog.where("lower(name) LIKE :search",
                        search: "%#{params[:search]}%")
    elsif params[:breed_id].to_i == 0
      @dogs = Dog.all
    else
      @dogs = Breed.find(params[:breed_id]).breed_dogs.map { |x| x.dog }
    end
  end

  def upvote
    dog = Dog.find(params[:id])
    dog.likes += 1
    dog.save
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @dogs = Dog.all.order("likes DESC").page(params[:page])
    render "dog/index" and return
  end

  def about; end
end

app/controllers/owner_controller.rb
class OwnerController < ApplicationController
  def index
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/breed_helper.rb
module BreedHelper
end

app/helpers/dog_helper.rb
module DogHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/owner_helper.rb
module OwnerHelper
end

app/views/breed/_breed_dog.html.erb
<div class="col">
  <div class="card" style="width: fit-content">
    <% if dog.image.present? %>
        <%= image_tag dog.image.variant(resize_to_limit: [405, 405]).processed, alt: "#{dog.name}"  %>
    <% end %>
    <div class="card-body">
      <h5 class="card-title"><%= dog.name.capitalize %></h5>
      <p class="card-text"><strong>Likes:</strong> <%= dog.likes %></p>
    </div>
    <ul class="list-group list-group-flush w-100">
      <li class="list-group-item w-100">
        <%= button_to dog, method: :get, class: "btn btn-primary w-100" do %>
          View Dog
        <% end %>
      </li>
    </ul>
  </div>
</div>

app/views/breed/_breed_list.html.erb
<tr>
  <td><%= breed.title.capitalize %></td>
  <td><%= breed.breed_dogs.count %></td>
  <td>
    <%= button_to breed, method: :get, class: "btn btn-primary" do %>
      View Breed Information
    <% end %>
  </td>
</tr>

app/views/breed/index.html.erb
<div class="container">
  <h2>Dog Breeds</h2>

  <hr />
  <%= paginate @breeds %>
  <table class="table table-striped">
    <thead class="table-dark">
      <tr>
        <th scope="col">Title</th>
        <th scope="col">Dogs Catalogued</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <%= render partial: "breed/breed_list", collection: @breeds, as: :breed %>
    </tbody>
  </table>
  <%= paginate @breeds %>
</div>

app/views/breed/show.html.erb
<div class="container">
  <div class="container">
    <h2><%= @breed.title.capitalize %></h2>
    <br />
    <hr />
    <p><strong>Dogs with this breed: </strong></p>
    <br />
    <%= paginate @dogs %>
    <section id="dogs" class="mt-5 mb-5 row row-cols-2">
      <%= render partial: "breed/breed_dog", collection: @dogs, as: :dog %>
    </section>
    <%= paginate @dogs %>
  </div>
</div>

app/views/dog/_dog_list.html.erb
<tr>
  <th scope="row"><%= ((params[:page].to_i-(params[:page].to_i > 1 ? 1 : 0)) * 25) + dog_counter + 1 %></th>
  <td><%= dog.likes %></td>
  <td>
    <% if dog.image.present? %>
        <%= image_tag dog.image.variant(resize_to_limit: [105, 105]).processed, alt: "#{dog.name}"  %>
    <% end %>
  </td>
  <td><%= dog.name.capitalize %></td>
  <td><%= dog.age %></td>
  <td><%= dog.gender %></td>
  <td>
    <%= button_to dog, method: :get, class: "btn btn-primary" do %>
      View Dog
    <% end %>
  </td>
</tr>

app/views/dog/_dog_search.html.erb
<li>
  <%= link_to dog.name.capitalize, dog %>
</>

app/views/dog/index.html.erb
<div class="container">
  <h2>Top Dogs</h2>
  <h4 class="mb-5">(Assorted by Likes)</h4>

  <hr />
  <%= paginate @dogs %>
  <table class="table table-striped">
    <thead class="table-dark">
      <tr>
        <th scope="col">#</th>
        <th scope="col">Likes</th>
        <th scope="col">Image</th>
        <th scope="col">Name</th>
        <th scope="col">Age</th>
        <th scope="col">Gender</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <%= render partial: "dog/dog_list", collection: @dogs, as: :dog %>
    </tbody>
  </table>
  <%= paginate @dogs %>
</div>

app/views/dog/search.html.erb
<div class="container">
  <h2>Search</h2>
  <p>Returned <%= @dogs.nil? ? "0" : @dogs.count %> entries.</p>

  <ul>
    <%= render partial: "dog/dog_search", collection: @dogs, as: :dog %>
  </ul>
</div>

app/views/dog/show.html.erb
<div class="container">
  <div class="row row-cols-3">
    <div class="col-5">
      <% if @dog.image.present? %>
          <%= image_tag @dog.image.variant(resize_to_limit: [505, 505]).processed, alt: "#{@dog.name}"  %>
      <% end %>
    </div>
    <div class="col-6">
      <h2><%= @dog.name.capitalize %></h2>
      <p><strong>Age:</strong> <%= @dog.age %></p>
      <p><strong>Gender:</strong> <%= @dog.gender %></p>
      <p><strong>Size:</strong> <%= @dog.size %></p>
      <p><strong>Owner:</strong> <%= link_to @dog.owner.name, @dog.owner %></p>
      <p><strong>Breed: </strong>
        <% @dog.breed_dogs.each.with_index do |breed_dog, index| %>
          <%= link_to breed_dog.breed.title, breed_dog.breed %>
          <%= @dog.breed_dogs.count-1 != index ? ", " : "" %>
        <% end %>
      </p>

    </div>
    <div  class="col mt-5">
      <h3><strong>Likes:</strong> <%= @dog.likes %></h3>
      <%= button_to "/dog/upvote/#{@dog.id}", method: :post, class: "btn btn-primary d-inline-block" do %>
        <i class="bi bi-hand-thumbs-up-fill"></i>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DogTag</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'shared/navbar' %>

    <main style="min-height:800px;margin-top:20px;">
      <%= yield %>
    </main>
    <br>
    <br>
    <br>
    <br>
    <br>
    <%= render partial: 'shared/footer' %>
  </body>
</html>

app/views/main/about.html.erb
<div class="container">
  <h2>About Us</h2>
  <hr />
  <p>DogTag is a non-profit organization in which individuals can share their lovely partners. In this website, visitors can see dog breeds, dogs, and their owners. They can also give like to the cute dogs in the website.</p>

  <%= image_tag ("IntroToRailsProjectProposalERD.drawio.png"), alt: "ERD" %>

  <br />
  <br />

  <h3>ERD</h3>
  <hr />
  <div class="container">
    <h4>Resources:</h4>
    <ul>
      <li>Dog API: <a href="https://dog.ceo/dog-api/">https://dog.ceo/dog-api/</a></li>
      <li>Faker Dataset: <a href="https://github.com/faker-ruby/faker">https://github.com/faker-ruby/faker</a></li>
    </ul>
  </div>
  <p><strong>Breed</strong>: The Breeds of the Dog resourced from the Dog API</p>
  <p><strong>Dog</strong>: The Dog records resourced from the Faker Dataset</p>
  <p><strong>Owner</strong>: The Owners of the Dog resourced from the Faker Dataset</p>
</div>

app/views/main/index.html.erb
<h1>Main#index</h1>
<p>Find me in app/views/main/index.html.erb</p>

app/views/owner/index.html.erb
<h1>Owner#index</h1>
<p>Find me in app/views/owner/index.html.erb</p>

app/views/owner/show.html.erb
<h1>Owner#show</h1>
<p>Find me in app/views/owner/show.html.erb</p>

app/views/shared/_footer.html.erb
<footer class="bg-secondary text-white pt-5 pb-5">
  <div class="container">
    <div class="row">
      <div class="col">
        DogTag
      </div>
      <div class="col">
        Contact Us
      </div>
      <div class="col">
        Help
        <div class="row ms-2">
          <div class="row">FAQs</div>
          <div class="row">Applying for your Dog</div>
          <div class="row">Registering your Owner Account</div>
          <div class="row"></div>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <%= link_to "DogTag", root_path, class: "navbar-brand", style: "font-size:30px;margin-left:10px;" %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse d-flex justify-content-between" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to "Home",  root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "About",  about_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Breeds",  breed_index_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Dogs",  root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Owners",  root_path, class: "nav-link" %>
          </li>
        </ul>

        <%= form_tag(dog_search_path, method: "post", class: "d-flex", style: "width:auto;position:relative;") do %>
          <%= search_field_tag :search, params[:search], placeholder: "Search Items", value: "", class: "form-control me-2"%>
          <%= select_tag :breed_id, options_for_select(Breed.all.map{|t| [t.title.capitalize, t.id]}.unshift(['All', '0']), selected: 0), class: "form-control me-2" %>
          <%= button_tag "Search", class: "btn btn-success"%>
        <% end %>
      </div>
  </div>
  </nav>
</header>